---
# tasks file for azure-sqldatabase
- name: Include copy Azure ID string if specified Copy mode
  include_vars:
    file: copy_db_vars.yml
  when: sql_createmode != "default"

- name: Run DB create
  include_tasks: azure-mssqldb.yml
  loop: "{{ sql_databases }}"